dist: xenial
language: go
go:
  - "1.11"
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
    - "$GOPATH/pkg/mod"
before_install:
  - |
    if [ ! -f "$HOME/google-cloud-sdk/bin/gcloud" ]; then
        curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-$GCLOUD_VERSION-linux-x86_64.tar.gz |
        tar -z -x -C $HOME -f -
    fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud --quiet components install app-engine-go
  - gcloud --quiet components install app-engine-python
  - if [ -n "$GCLOUD_VERSION" ]; then gcloud --quiet components update --version $GCLOUD_VERSION; fi
  - gcloud version
install: true
script:
  - go test -v -coverprofile=coverage.txt -covermode=count ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - GCLOUD_VERSION=231.0.0
    - GO111MODULE=on
