language: go
go:
- 1.8.1
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
before_install:
- if [ ! -f "$HOME/google-cloud-sdk/bin/gcloud" ]; then curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-$GCLOUD_VERSION-linux-x86_64.tar.gz
  && tar -x -C $HOME -f google-cloud-sdk-$GCLOUD_VERSION-linux-x86_64.tar.gz; fi
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud --quiet components install app-engine-go
- gcloud --quiet components install app-engine-python
- gcloud --quiet components update --version $GCLOUD_VERSION
install:
- go get -t -d -v ./...
script:
- go test -coverprofile=coverage.txt -covermode=count
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- openssl aes-256-cbc -K $encrypted_b04a62d8fcad_key -iv $encrypted_b04a62d8fcad_iv
  -in travis-ci-service-account.json.enc -out travis-ci-service-account.json -d
- openssl aes-256-cbc -K $encrypted_b04a62d8fcad_key -iv $encrypted_b04a62d8fcad_iv
  -in staging.app.yaml.enc -out staging.app.yaml -d
deploy:
- gcloud auth activate-service-account --key-file travis-ci-service-account.json
- gcloud --quiet app --project bus-eta-bot deploy staging.app.yaml
env:
- GCLOUD_VERSION=155.0.0
